using Quadrant.Core.Enums; using Quadrant.Core.Interfaces; using Quadrant.Core.Models;
namespace Quadrant.Core.Services;
public sealed class PomodoroTimerService
{
 private readonly IFocusSessionService sessions; private readonly IClock clock; private readonly IFocusCompletionScheduler scheduler; private FocusSession? current; private PomodoroSettings? settings; private IDisposable? scheduled; private int generation; private int productiveCount;
 public PomodoroTimerService(IFocusSessionService sessions,IClock clock,IFocusCompletionScheduler scheduler){this.sessions=sessions;this.clock=clock;this.scheduler=scheduler;}
 public FocusSession? Current=>current; public int RemainingSeconds=>current?.TargetEndAtUtc is { } end?(int)Math.Max(0,Math.Floor((end-clock.UtcNow).TotalSeconds)):0; public PomodoroKind? SuggestedNextKind {get;private set;}
 public async Task<FocusSession> StartAsync(long? taskId,PomodoroKind kind,PomodoroSettings snapshot,CancellationToken ct=default){if(current is not null)throw new InvalidOperationException("A Pomodoro session is already active.");snapshot.Validate();settings=snapshot;var now=clock.UtcNow;var duration=Duration(kind,snapshot);current=await sessions.StartAsync(new FocusSessionStartRequest(kind==PomodoroKind.Focus?taskId:null,FocusMode.Pomodoro,kind,now.AddMinutes(duration)),ct);Arm();return current;}
 public async Task<FocusSession> PauseAsync(CancellationToken ct=default){var s=Require(FocusStatus.Running);DisposeTimer();var elapsed=s.TargetEndAtUtc is { } end?Duration(s.PomodoroKind!.Value,settings!)*60-Math.Max(0,(int)Math.Ceiling((end-clock.UtcNow).TotalSeconds)):0;current=await sessions.PauseAsync(s.Id,elapsed,clock.UtcNow,ct);return current;}
 public async Task<FocusSession> ResumeAsync(CancellationToken ct=default){var s=Require(FocusStatus.Paused);var remaining=Math.Max(0,Duration(s.PomodoroKind!.Value,settings!)*60-s.DurationSeconds);var end=clock.UtcNow.AddSeconds(remaining);current=await sessions.ResumeAsync(s.Id,clock.UtcNow,end,ct);Arm();return current;}
 public async Task<FocusSession> StopAsync(CancellationToken ct=default){var s=Require(FocusStatus.Running,FocusStatus.Paused);DisposeTimer();current=null;var r=await sessions.CompleteAsync(s.Id,Elapsed(s),clock.UtcNow,ct);AfterComplete(r);return r;}
 public async Task<FocusSession> CancelAsync(CancellationToken ct=default){var s=Require(FocusStatus.Running,FocusStatus.Paused);DisposeTimer();current=null;return await sessions.CancelAsync(s.Id,Elapsed(s),clock.UtcNow,ct);}
 private void Arm(){DisposeTimer();var captured=++generation;var id=current!.Id;scheduled=scheduler.Schedule(current.TargetEndAtUtc!.Value,async()=>{if(captured!=generation||current?.Id!=id)return;try{await StopAsync();}catch(InvalidOperationException){}});}
 private void AfterComplete(FocusSession s){if(s.PomodoroKind==PomodoroKind.Focus){productiveCount++;SuggestedNextKind=productiveCount%settings!.LongBreakInterval==0?PomodoroKind.LongBreak:PomodoroKind.ShortBreak;}else SuggestedNextKind=PomodoroKind.Focus;}
 private int Elapsed(FocusSession s)=>s.Status==FocusStatus.Paused?s.DurationSeconds:Duration(s.PomodoroKind!.Value,settings!)*60-RemainingSeconds;
 private FocusSession Require(params FocusStatus[] allowed)=>current is not null&&allowed.Contains(current.Status)?current:throw new InvalidOperationException("Pomodoro is not in a valid state."); private int Duration(PomodoroKind k,PomodoroSettings p)=>k switch{PomodoroKind.Focus=>p.FocusMinutes,PomodoroKind.ShortBreak=>p.ShortBreakMinutes,_=>p.LongBreakMinutes}; private void DisposeTimer(){generation++;scheduled?.Dispose();scheduled=null;}
}
